<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-10 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
=======
# Generated by Django 5.2.5 on 2025-08-25 10:44

import django.db.models.deletion
>>>>>>> gitlab/tripboard-import
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> gitlab/tripboard-import
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
<<<<<<< HEAD
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_shared_readonly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='boards.board')),
            ],
            options={
                'ordering': ('position', 'created_at'),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='board_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boards',
                'ordering': ['-created_at'],
>>>>>>> gitlab/tripboard-import
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
<<<<<<< HEAD
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('people', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.list')),
            ],
            options={
                'ordering': ('position', 'created_at'),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('people_number', models.PositiveIntegerField(default=1)),
                ('tags', models.JSONField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.list'))),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtasks', models.JSONField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.list'))),
                ('attachments', models.JSONField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.list'))),
                ('location', models.JSONField(blank=True, default=dict, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cards',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lists',
                'ordering': ['position'],
>>>>>>> gitlab/tripboard-import
            },
        ),
    ]
