# Generated by Django 5.2.4 on 2025-08-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['list', 'position'], name='boards_card_list_id_1ea5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['board', 'position'], name='boards_list_board_i_ada2a2_idx'),
        ),
    ]
