# Generated by Django 5.2.4 on 2025-08-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_card_position_alter_list_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('position', 'created_at', 'id')},
        ),
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('board', 'position'), name='uniq_board_pos'),
        ),
    ]
