# Generated by Django 5.2.5 on 2025-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
