# Generated by Django 5.2.5 on 2025-08-27 15:31

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tags',
            field=models.JSONField(default=boards.models.get_default_list),
        ),
        migrations.AlterField(
            model_name='card',
            name='attachments',
            field=models.JSONField(default=boards.models.get_default_list),
        ),
        migrations.AlterField(
            model_name='card',
            name='location',
            field=models.JSONField(blank=True, default=boards.models.get_default_dict, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtasks',
            field=models.JSONField(default=boards.models.get_default_list),
        ),
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.JSONField(default=boards.models.get_default_list),
        ),
    ]
