# Generated by Django 5.2.4 on 2025-08-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_list_options_alter_list_position_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='list',
            name='uniq_board_pos',
        ),
    ]
