# Generated by Django 5.2.5 on 2025-08-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_board_tags_alter_card_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(blank=True, choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('food', 'Food'), ('activity', 'Activity'), ('romantic', 'Romantic'), ('family', 'Family')], max_length=20, null=True),
        ),
    ]
