# Generated by Django 5.2.4 on 2025-08-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_list_uniq_board_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
